сформировать базу данных из трёх таблиц
"студенты" (имя, фамилия, группа)
"группы" (название группы, факультет)
"факультеты" (название факультета, количество предметов)

первая таблица должна хранить id групп, вторая - id факультетов

Получить из таблицы студентов их ФИО и количество предметов
Получить количество студентов каждого факультета

In [183]:
import sqlite3 as sq3
import pandas as pd

In [165]:
con = sq3.connect("university.db")

In [166]:
cursor = con.cursor()

In [167]:
cursor.execute("""CREATE TABLE faculty(
              id INTEGER PRIMARY KEY AUTOINCREMENT,
              name TEXT NOT NULL,
              quantity_group INTEGER NOT NULL
)""")
cursor.execute("""CREATE TABLE groups(
              id INTEGER PRIMARY KEY AUTOINCREMENT,
              name TEXT NOT NULL,
              faculty_id INTEGER NOT NULL,
              FOREIGN KEY (faculty_id) REFERENCES faculty (id)
)""")
cursor.execute("""CREATE TABLE students(
              id INTEGER PRIMARY KEY AUTOINCREMENT,
              surname TEXT NOT NULL,
              name TEXT NOT NULL,
              group_id INTEGER NOT NULL,
              FOREIGN KEY (group_id) REFERENCES groups (id)
)""")

In [168]:
con.commit()

In [169]:
cursor.execute("SELECT * FROM sqlite_master")
cursor.fetchall()

[('table',
  'faculty',
  'faculty',
  2,
  'CREATE TABLE faculty(\n              id INTEGER PRIMARY KEY AUTOINCREMENT,\n              name TEXT NOT NULL,\n              quantity_group INTEGER NOT NULL \n)'),
 ('table',
  'sqlite_sequence',
  'sqlite_sequence',
  3,
  'CREATE TABLE sqlite_sequence(name,seq)'),
 ('table',
  'groups',
  'groups',
  4,
  'CREATE TABLE groups(\n              id INTEGER PRIMARY KEY AUTOINCREMENT,\n              name TEXT NOT NULL,\n              faculty_id INTEGER NOT NULL,\n              FOREIGN KEY (faculty_id) REFERENCES faculty (id)\n)'),
 ('table',
  'students',
  'students',
  5,
  'CREATE TABLE students(\n              id INTEGER PRIMARY KEY AUTOINCREMENT,\n              surname TEXT NOT NULL,\n              name TEXT NOT NULL,\n              group_id INTEGER NOT NULL,\n              FOREIGN KEY (group_id) REFERENCES groups (id)\n)')]

In [170]:
cursor.execute("""INSERT INTO faculty(name, quantity_group) VALUES ('Факультет автоматической электросвязи', 10),
                                                   ('Факультет информатики и вычислительной техники', 12),
                                                   ('Факультет мобильной радиосвязи и мультимедиа', 9),
                                                   ('Факультет мультисервисных телекоммуникационных систем', 14)
              """)

In [171]:
con.commit()

In [172]:
cursor.execute("SELECT * FROM faculty")
cursor.fetchall()

[(1, 'Факультет автоматической электросвязи', 4),
 (2, 'Факультет информатики и вычислительной техники', 3),
 (3, 'Факультет мобильной радиосвязи и мультимедиа', 6),
 (4, 'Факультет мультисервисных телекоммуникационных систем', 3)]

In [173]:
cursor.execute("""INSERT INTO groups(name, faculty_id) VALUES
              ('Инфокоммуникационные технологии и системы связи', 1),
              ('Инфокоммуникационные технологии системы специальной связи', 1),
              ('Информационная безопасность', 1),
              ('Информационная безопасность телекоммуникационных систем', 1),
              ('Бизнес-информатика', 2),
              ('Информатика и вычислительная техника', 2),
              ('Прикладная информатика', 2),
              ('Инфокоммуникационные технологии и системы связи', 3),
              ('Информационные системы и технологии', 3),
              ('Конструирование и технология электронных средств', 3),
              ('Радиотехника', 3),
              ('Радиоэлектронные системы и комплексы', 3),
              ('Специальные радиотехнические системы', 3),
              ('Инфокоммуникационные технологии и системы связи', 4),
              ('Конструирование и технология электронных средств', 4),
              ('Электроника и наноэлектроника', 4)
              """)

In [174]:
con.commit()

In [175]:
cursor.execute("SELECT * FROM groups")
cursor.fetchall()

[(1, 'Инфокоммуникационные технологии и системы связи', 1),
 (2, 'Инфокоммуникационные технологии системы специальной связи', 1),
 (3, 'Информационная безопасность', 1),
 (4, 'Информационная безопасность телекоммуникационных систем', 1),
 (5, 'Бизнес-информатика', 2),
 (6, 'Информатика и вычислительная техника', 2),
 (7, 'Прикладная информатика', 2),
 (8, 'Инфокоммуникационные технологии и системы связи', 3),
 (9, 'Информационные системы и технологии', 3),
 (10, 'Конструирование и технология электронных средств', 3),
 (11, 'Радиотехника', 3),
 (12, 'Радиоэлектронные системы и комплексы', 3),
 (13, 'Специальные радиотехнические системы', 3),
 (14, 'Инфокоммуникационные технологии и системы связи', 4),
 (15, 'Конструирование и технология электронных средств', 4),
 (16, 'Электроника и наноэлектроника', 4)]

In [178]:
students_list = [('Авдиенко', 'Павел Савванович', 10),
('Агеева', 'Арина Ивановна', 8),
('Алешина', 'Лидия Васильевна', 1),
('Анников', 'Тимофей Ильич', 1),
('Артамонов', 'Константин Елизарович', 8),
('Баженов', 'Денис Юрьевич', 6),
('Балдагуев', 'Игнат Панкратович', 3),
('Балыкова', 'Клара Петровна', 4),
('Беликова', 'Аполлинария Максимовна', 9),
('Белоусова', 'Василиса Федоровна', 5),
('Бирюкова', 'Рада Кирилловна', 3),
('Боньча', 'Елена Константиновна', 2),
('Буданова', 'Оксана Семеновна', 15),
('Ванзин', 'Петр Прокльев', 4),
('Вахрушева', 'Евгения Никифоровна', 7),
('Витинская', 'Александра Кузьминовна', 11),
('Владмимирцева', 'Елизавета Владимировна', 2),
('Водоватов', 'Виктор Романович', 7),
('Водянов', 'Аркадий Игнатьевич', 13),
('Володин', 'Петр Леонидович', 3),
('Воронцова', 'Нина Васильевна', 7),
('Гагарина', 'Жанна Тимофеевна', 16),
('Гайдукова', 'Лана Ефимовна', 15),
('Галкин', 'Степан Иннокентиевич', 10),
('Голикова', 'Тамара Степановна', 5),
('Гроссман', 'Федот Николаевич', 5),
('Гудкова', 'Ксения Ивановна', 1),
('Данькина', 'Ася Валерьевна', 16),
('Долгов', 'Тарас Егорович', 8),
('Дорофеев', 'Сергей Павлович', 8),
('Драке', 'Георгий Порфирьевич', 12),
('Дуванова', 'Рада Климентьевна', 13),
('Дябина', 'Кира Герасимовна', 12),
('Емельянов', 'Кузьма Климентович', 6),
('Жевлакова', 'Юлиана Арсеньевна', 14),
('Жукова', 'Анжела Ипполитовна', 9),
('Журавлёв', 'Аркадий Семенович', 10),
('Задорнова', 'Зинаида Тимофеевна', 13),
('Задорнова', 'Степанида Тимофеевна', 14),
('Иванов', 'Никита Сергеевич', 3),
('Кабинова', 'Светлана Иннокентьевна', 13),
('Канадин', 'Михаил Константинович', 3),
('Капнист', 'Ольга Ивановна', 11),
('Карпенцева', 'Александра Трофимовна', 4),
('Карпюк', 'Татьяна Семеновна', 12),
('Каца', 'Ася Ефимовна', 8),
('Каширина', 'Ирина Федоровна', 9),
('Кваснина', 'Ксения Ильишна', 15),
('Клецка', 'Ирина Никандровна', 7),
('Козлова', 'Анжела Афанасьевна', 1),
('Койначёнока', 'Мария Михаиловна', 1),
('Койтасбаева', 'Евгения Ивановна', 6),
('Кокорев', 'Василий Тимофеевич', 10),
('Корнилова', 'Алиса Севастьяновна', 13),
('Коровин', 'Александр Федорович', 2),
('Кравкова', 'Людмила Викторовна', 6),
('Кручинкина', 'Серафима Ефимовна', 10),
('Кузинов', 'Семен Федотович', 10),
('Куксова', 'Таисия Трофимовна', 9),
('Купревич', 'Вера Нифонтовна', 5),
('Кутюков', 'Геннадий Юлианович', 8),
('Куусинен', 'Семен Давидович', 8),
('Латышев', 'Евгений Юрьевич', 15),
('Лашманова', 'Вероника Денисовна', 13),
('Ленинг', 'Нина Михайловна', 4),
('Лесков', 'Севастьян Константинович', 7),
('Логиновская', 'Екатерина Давидовна', 12),
('Лукова', 'Виктория Петровна', 15),
('Малец', 'Анастасия Давидович', 12),
('Мамыкин', 'Степан Вениаминович', 10),
('Матвиенко', 'Константин Степанович', 2),
('Мельников', 'Юрий Прокопьевич', 10),
('Михайличенко', 'Павел Кириллович', 13),
('Мишуринский', 'Ростислав Васильевич', 6),
('Мосякова', 'Алена Саввановна', 7),
('Низовцев', 'Василий Наумович', 1),
('Никитин', 'Семен Ефимович', 14),
('Никулаичева', 'Полина Егоровна', 14),
('Новицкая', 'Надежда Ивановна', 8),
('Ноздрин', 'Георгий Викторович', 3),
('Овчинникова', 'Екатерина Кирилловна', 6),
('Осинов', 'Захар Тарасович', 9),
('Павлова', 'Афанасия Игнатевна', 4),
('Пайков', 'Кирилл Данилович', 5),
('Пайков', 'Степан Данилович', 6),
('Песков', 'Иван Ираклиевич', 12),
('Петрищев', 'Тимофей Максимович', 2),
('Петрова', 'Дарья Сергеевна', 5),
('Петрунин', 'Максим Петрович', 11),
('Погодов', 'Адам Нифонтович', 6),
('Подчасов', 'Максим Никанорович', 14),
('Покалюк', 'Лаврентий Степанович', 14),
('Полкова', 'Юлиана Всеволодовна', 1),
('Полторак', 'Севастьян Кириллович', 8),
('Попов', 'Лев Венедиктович', 12),
('Пузанова', 'Любовь Никитьевна', 4),
('Пушкина', 'Александра Кирилловна', 13),
('Пшеничников', 'Афанасий Васильевич', 4),
('Рабиновича', 'Ирина Ивановна', 2),
('Райт', 'Марианна Трофимовна', 9),
('Редругина', 'Вера Николаевна', 8),
('Романенко', 'Валентина Никифоровна', 16),
('Ростовцев', 'Егор Елизарович', 10),
('Рошета', 'Виктория Ивановна', 11),
('Рудина', 'Алла Юрьевна', 11),
('Русакова', 'Валентина Климентьевна', 16),
('Русакова', 'Марина Петровна', 6),
('Садков', 'Роман Степанович', 13),
('Сальков', 'Макар Аркадинович', 7),
('Саянкин', 'Кирилл Леонидович', 11),
('Седов', 'Игнат Николаевич', 15),
('Сенькина', 'Надежда Федотовна', 1),
('Серёгина', 'Арина Макаровна', 2),
('Сидорова', 'Наталья Васильевна', 7),
('Силаева', 'Светлана Ираклиевна', 4),
('Сиясинов', 'Кирилл Леонтьевич', 7),
('Славакова', 'Анжела Никитьевна', 4),
('Слукина', 'Серафима Максимовна', 2),
('Сонин', 'Савва Геннадьевич', 16),
('Сочинская', 'Валентина Якововна', 16),
('Сухих', 'Людмила Никифоровна', 3),
('Сухиха', 'Юлиана Романовна', 2),
('Сучкова', 'Серафима Ростиславовна', 10),
('Сычёва', 'Лариса Ростиславовна', 3),
('Тарасова', 'Василиса Павловна', 9),
('Травкина', 'Сюзанна Петровна', 13),
('Троицкий', 'Тимофей Юлианович', 9),
('Уицкая', 'Сюзанна Ростиславовна', 4),
('Хабаров', 'Макар Витальевич', 5),
('Халипов', 'Максим Петрович', 15),
('Ховрунов', 'Артем Филиппович', 14),
('Хохлова', 'Мила Себастьяновна', 3),
('Хренова', 'Нина Константиновна', 16),
('Чегодаев', 'Егор Савванович', 1),
('Черкашина', 'Сюзанна Прохор', 14),
('Чиркова', 'Марьяна Ираклиевна', 16),
('Чуличкова', 'Валерия Феоктистовна', 5),
('Швечикова', 'Светлана Петровна', 12),
('Шелепина', 'Василиса Ростиславовна', 5),
('Шерстов', 'Валерий Макарович', 1),
('Шумова', 'Алла Павловна', 12),
('Щенин', 'Яков Филиппович', 3),
('Щередина', 'Анна Константиновна', 12),
('Эпингера', 'Рада Иннокентьевна', 6),
('Ягодин', 'Роман Даниилович', 5),
('Якобсона', 'Раиса Макаровна', 16),
('Яковиченко', 'Пелагея Никитьевна', 16),
('Яковцов', 'Лаврентий Петрович', 11),
('Яковцова', 'Елизавета Трофимовна', 14),
('Якубовский', 'Роман Петрович', 15),
('Якшина', 'Виктория Юрьевна', 9),
('Ямсков', 'Гавриил Максимович', 2),
('Ямщикова', 'Ксения Николаевна', 15),
('Ярочкин', 'Антон Ефимович', 11),
('Ярочкин', 'Юрин Давидович', 11),
('Ярощук', 'Афанасий Михаилович', 11),
('Ясавеева', 'Александра Ефимовна', 15),
('Яхонтов', 'Федор Игнатьевич', 14),
('Яцунова', 'Галина Якововна', 9)]

In [179]:
cursor.executemany("INSERT INTO students(surname, name,  group_id) VALUES (?, ?, ?)", students_list)

In [180]:
con.commit()

In [181]:
cursor.execute("SELECT * FROM students")
cursor.fetchall()

[(1, 'Авдиенко', 'Павел Савванович', 10),
 (2, 'Агеева', 'Арина Ивановна', 8),
 (3, 'Алешина', 'Лидия Васильевна', 1),
 (4, 'Анников', 'Тимофей Ильич', 1),
 (5, 'Артамонов', 'Константин Елизарович', 8),
 (6, 'Баженов', 'Денис Юрьевич', 6),
 (7, 'Балдагуев', 'Игнат Панкратович', 3),
 (8, 'Балыкова', 'Клара Петровна', 4),
 (9, 'Беликова', 'Аполлинария Максимовна', 9),
 (10, 'Белоусова', 'Василиса Федоровна', 5),
 (11, 'Бирюкова', 'Рада Кирилловна', 3),
 (12, 'Боньча', 'Елена Константиновна', 2),
 (13, 'Буданова', 'Оксана Семеновна', 15),
 (14, 'Ванзин', 'Петр Прокльев', 4),
 (15, 'Вахрушева', 'Евгения Никифоровна', 7),
 (16, 'Витинская', 'Александра Кузьминовна', 11),
 (17, 'Владмимирцева', 'Елизавета Владимировна', 2),
 (18, 'Водоватов', 'Виктор Романович', 7),
 (19, 'Водянов', 'Аркадий Игнатьевич', 13),
 (20, 'Володин', 'Петр Леонидович', 3),
 (21, 'Воронцова', 'Нина Васильевна', 7),
 (22, 'Гагарина', 'Жанна Тимофеевна', 16),
 (23, 'Гайдукова', 'Лана Ефимовна', 15),
 (24, 'Галкин', 'Степан Иннокентиевич', 10),
 (25, 'Голикова', 'Тамара Степановна', 5),
 (26, 'Гроссман', 'Федот Николаевич', 5),
 (27, 'Гудкова', 'Ксения Ивановна', 1),
 (28, 'Данькина', 'Ася Валерьевна', 16),
 (29, 'Долгов', 'Тарас Егорович', 8),
 (30, 'Дорофеев', 'Сергей Павлович', 8),
 (31, 'Драке', 'Георгий Порфирьевич', 12),
 (32, 'Дуванова', 'Рада Климентьевна', 13),
 (33, 'Дябина', 'Кира Герасимовна', 12),
 (34, 'Емельянов', 'Кузьма Климентович', 6),
 (35, 'Жевлакова', 'Юлиана Арсеньевна', 14),
 (36, 'Жукова', 'Анжела Ипполитовна', 9),
 (37, 'Журавлёв', 'Аркадий Семенович', 10),
 (38, 'Задорнова', 'Зинаида Тимофеевна', 13),
 (39, 'Задорнова', 'Степанида Тимофеевна', 14),
 (40, 'Иванов', 'Никита Сергеевич', 3),
 (41, 'Кабинова', 'Светлана Иннокентьевна', 13),
 (42, 'Канадин', 'Михаил Константинович', 3),
 (43, 'Капнист', 'Ольга Ивановна', 11),
 (44, 'Карпенцева', 'Александра Трофимовна', 4),
 (45, 'Карпюк', 'Татьяна Семеновна', 12),
 (46, 'Каца', 'Ася Ефимовна', 8),
 (47, 'Каширина', 'Ирина Федоровна', 9),
 (48, 'Кваснина', 'Ксения Ильишна', 15),
 (49, 'Клецка', 'Ирина Никандровна', 7),
 (50, 'Козлова', 'Анжела Афанасьевна', 1),
 (51, 'Койначёнока', 'Мария Михаиловна', 1),
 (52, 'Койтасбаева', 'Евгения Ивановна', 6),
 (53, 'Кокорев', 'Василий Тимофеевич', 10),
 (54, 'Корнилова', 'Алиса Севастьяновна', 13),
 (55, 'Коровин', 'Александр Федорович', 2),
 (56, 'Кравкова', 'Людмила Викторовна', 6),
 (57, 'Кручинкина', 'Серафима Ефимовна', 10),
 (58, 'Кузинов', 'Семен Федотович', 10),
 (59, 'Куксова', 'Таисия Трофимовна', 9),
 (60, 'Купревич', 'Вера Нифонтовна', 5),
 (61, 'Кутюков', 'Геннадий Юлианович', 8),
 (62, 'Куусинен', 'Семен Давидович', 8),
 (63, 'Латышев', 'Евгений Юрьевич', 15),
 (64, 'Лашманова', 'Вероника Денисовна', 13),
 (65, 'Ленинг', 'Нина Михайловна', 4),
 (66, 'Лесков', 'Севастьян Константинович', 7),
 (67, 'Логиновская', 'Екатерина Давидовна', 12),
 (68, 'Лукова', 'Виктория Петровна', 15),
 (69, 'Малец', 'Анастасия Давидович', 12),
 (70, 'Мамыкин', 'Степан Вениаминович', 10),
 (71, 'Матвиенко', 'Константин Степанович', 2),
 (72, 'Мельников', 'Юрий Прокопьевич', 10),
 (73, 'Михайличенко', 'Павел Кириллович', 13),
 (74, 'Мишуринский', 'Ростислав Васильевич', 6),
 (75, 'Мосякова', 'Алена Саввановна', 7),
 (76, 'Низовцев', 'Василий Наумович', 1),
 (77, 'Никитин', 'Семен Ефимович', 14),
 (78, 'Никулаичева', 'Полина Егоровна', 14),
 (79, 'Новицкая', 'Надежда Ивановна', 8),
 (80, 'Ноздрин', 'Георгий Викторович', 3),
 (81, 'Овчинникова', 'Екатерина Кирилловна', 6),
 (82, 'Осинов', 'Захар Тарасович', 9),
 (83, 'Павлова', 'Афанасия Игнатевна', 4),
 (84, 'Пайков', 'Кирилл Данилович', 5),
 (85, 'Пайков', 'Степан Данилович', 6),
 (86, 'Песков', 'Иван Ираклиевич', 12),
 (87, 'Петрищев', 'Тимофей Максимович', 2),
 (88, 'Петрова', 'Дарья Сергеевна', 5),
 (89, 'Петрунин', 'Максим Петрович', 11),
 (90, 'Погодов', 'Адам Нифонтович', 6),
 (91, 'Подчасов', 'Максим Никанорович', 14),
 (92, 'Покалюк', 'Лаврентий Степанович', 14),
 (93, 'Полкова', 'Юлиана Всеволодовна', 1),
 (94, 'Полторак', 'Севастьян Кириллович', 8),
 (95, 'Попов', 'Лев Венедиктович', 12),
 (96, 'Пузанова', 'Любовь Никитьевна', 4),
 (97, 'Пушкина', 'Александра Кирилловна', 13),
 (98, 'Пшеничников', 'Афанасий Васильевич', 4),
 (99, 'Рабиновича', 'Ирина Ивановна', 2),
 (100, 'Райт', 'Марианна Трофимовна', 9),
 (101, 'Редругина', 'Вера Николаевна', 8),
 (102, 'Романенко', 'Валентина Никифоровна', 16),
 (103, 'Ростовцев', 'Егор Елизарович', 10),
 (104, 'Рошета', 'Виктория Ивановна', 11),
 (105, 'Рудина', 'Алла Юрьевна', 11),
 (106, 'Русакова', 'Валентина Климентьевна', 16),
 (107, 'Русакова', 'Марина Петровна', 6),
 (108, 'Садков', 'Роман Степанович', 13),
 (109, 'Сальков', 'Макар Аркадинович', 7),
 (110, 'Саянкин', 'Кирилл Леонидович', 11),
 (111, 'Седов', 'Игнат Николаевич', 15),
 (112, 'Сенькина', 'Надежда Федотовна', 1),
 (113, 'Серёгина', 'Арина Макаровна', 2),
 (114, 'Сидорова', 'Наталья Васильевна', 7),
 (115, 'Силаева', 'Светлана Ираклиевна', 4),
 (116, 'Сиясинов', 'Кирилл Леонтьевич', 7),
 (117, 'Славакова', 'Анжела Никитьевна', 4),
 (118, 'Слукина', 'Серафима Максимовна', 2),
 (119, 'Сонин', 'Савва Геннадьевич', 16),
 (120, 'Сочинская', 'Валентина Якововна', 16),
 (121, 'Сухих', 'Людмила Никифоровна', 3),
 (122, 'Сухиха', 'Юлиана Романовна', 2),
 (123, 'Сучкова', 'Серафима Ростиславовна', 10),
 (124, 'Сычёва', 'Лариса Ростиславовна', 3),
 (125, 'Тарасова', 'Василиса Павловна', 9),
 (126, 'Травкина', 'Сюзанна Петровна', 13),
 (127, 'Троицкий', 'Тимофей Юлианович', 9),
 (128, 'Уицкая', 'Сюзанна Ростиславовна', 4),
 (129, 'Хабаров', 'Макар Витальевич', 5),
 (130, 'Халипов', 'Максим Петрович', 15),
 (131, 'Ховрунов', 'Артем Филиппович', 14),
 (132, 'Хохлова', 'Мила Себастьяновна', 3),
 (133, 'Хренова', 'Нина Константиновна', 16),
 (134, 'Чегодаев', 'Егор Савванович', 1),
 (135, 'Черкашина', 'Сюзанна Прохор', 14),
 (136, 'Чиркова', 'Марьяна Ираклиевна', 16),
 (137, 'Чуличкова', 'Валерия Феоктистовна', 5),
 (138, 'Швечикова', 'Светлана Петровна', 12),
 (139, 'Шелепина', 'Василиса Ростиславовна', 5),
 (140, 'Шерстов', 'Валерий Макарович', 1),
 (141, 'Шумова', 'Алла Павловна', 12),
 (142, 'Щенин', 'Яков Филиппович', 3),
 (143, 'Щередина', 'Анна Константиновна', 12),
 (144, 'Эпингера', 'Рада Иннокентьевна', 6),
 (145, 'Ягодин', 'Роман Даниилович', 5),
 (146, 'Якобсона', 'Раиса Макаровна', 16),
 (147, 'Яковиченко', 'Пелагея Никитьевна', 16),
 (148, 'Яковцов', 'Лаврентий Петрович', 11),
 (149, 'Яковцова', 'Елизавета Трофимовна', 14),
 (150, 'Якубовский', 'Роман Петрович', 15),
 (151, 'Якшина', 'Виктория Юрьевна', 9),
 (152, 'Ямсков', 'Гавриил Максимович', 2),
 (153, 'Ямщикова', 'Ксения Николаевна', 15),
 (154, 'Ярочкин', 'Антон Ефимович', 11),
 (155, 'Ярочкин', 'Юрин Давидович', 11),
 (156, 'Ярощук', 'Афанасий Михаилович', 11),
 (157, 'Ясавеева', 'Александра Ефимовна', 15),
 (158, 'Яхонтов', 'Федор Игнатьевич', 14),
 (159, 'Яцунова', 'Галина Якововна', 9)]

In [198]:
cursor.execute("SELECT (surname||' '||name) FROM students")
cursor.fetchall()

[('Авдиенко Павел Савванович',),
 ('Агеева Арина Ивановна',),
 ('Алешина Лидия Васильевна',),
 ('Анников Тимофей Ильич',),
 ('Артамонов Константин Елизарович',),
 ('Баженов Денис Юрьевич',),
 ('Балдагуев Игнат Панкратович',),
 ('Балыкова Клара Петровна',),
 ('Беликова Аполлинария Максимовна',),
 ('Белоусова Василиса Федоровна',),
 ('Бирюкова Рада Кирилловна',),
 ('Боньча Елена Константиновна',),
 ('Буданова Оксана Семеновна',),
 ('Ванзин Петр Прокльев',),
 ('Вахрушева Евгения Никифоровна',),
 ('Витинская Александра Кузьминовна',),
 ('Владмимирцева Елизавета Владимировна',),
 ('Водоватов Виктор Романович',),
 ('Водянов Аркадий Игнатьевич',),
 ('Володин Петр Леонидович',),
 ('Воронцова Нина Васильевна',),
 ('Гагарина Жанна Тимофеевна',),
 ('Гайдукова Лана Ефимовна',),
 ('Галкин Степан Иннокентиевич',),
 ('Голикова Тамара Степановна',),
 ('Гроссман Федот Николаевич',),
 ('Гудкова Ксения Ивановна',),
 ('Данькина Ася Валерьевна',),
 ('Долгов Тарас Егорович',),
 ('Дорофеев Сергей Павлович',),
 ('Драке Георгий Порфирьевич',),
 ('Дуванова Рада Климентьевна',),
 ('Дябина Кира Герасимовна',),
 ('Емельянов Кузьма Климентович',),
 ('Жевлакова Юлиана Арсеньевна',),
 ('Жукова Анжела Ипполитовна',),
 ('Журавлёв Аркадий Семенович',),
 ('Задорнова Зинаида Тимофеевна',),
 ('Задорнова Степанида Тимофеевна',),
 ('Иванов Никита Сергеевич',),
 ('Кабинова Светлана Иннокентьевна',),
 ('Канадин Михаил Константинович',),
 ('Капнист Ольга Ивановна',),
 ('Карпенцева Александра Трофимовна',),
 ('Карпюк Татьяна Семеновна',),
 ('Каца Ася Ефимовна',),
 ('Каширина Ирина Федоровна',),
 ('Кваснина Ксения Ильишна',),
 ('Клецка Ирина Никандровна',),
 ('Козлова Анжела Афанасьевна',),
 ('Койначёнока Мария Михаиловна',),
 ('Койтасбаева Евгения Ивановна',),
 ('Кокорев Василий Тимофеевич',),
 ('Корнилова Алиса Севастьяновна',),
 ('Коровин Александр Федорович',),
 ('Кравкова Людмила Викторовна',),
 ('Кручинкина Серафима Ефимовна',),
 ('Кузинов Семен Федотович',),
 ('Куксова Таисия Трофимовна',),
 ('Купревич Вера Нифонтовна',),
 ('Кутюков Геннадий Юлианович',),
 ('Куусинен Семен Давидович',),
 ('Латышев Евгений Юрьевич',),
 ('Лашманова Вероника Денисовна',),
 ('Ленинг Нина Михайловна',),
 ('Лесков Севастьян Константинович',),
 ('Логиновская Екатерина Давидовна',),
 ('Лукова Виктория Петровна',),
 ('Малец Анастасия Давидович',),
 ('Мамыкин Степан Вениаминович',),
 ('Матвиенко Константин Степанович',),
 ('Мельников Юрий Прокопьевич',),
 ('Михайличенко Павел Кириллович',),
 ('Мишуринский Ростислав Васильевич',),
 ('Мосякова Алена Саввановна',),
 ('Низовцев Василий Наумович',),
 ('Никитин Семен Ефимович',),
 ('Никулаичева Полина Егоровна',),
 ('Новицкая Надежда Ивановна',),
 ('Ноздрин Георгий Викторович',),
 ('Овчинникова Екатерина Кирилловна',),
 ('Осинов Захар Тарасович',),
 ('Павлова Афанасия Игнатевна',),
 ('Пайков Кирилл Данилович',),
 ('Пайков Степан Данилович',),
 ('Песков Иван Ираклиевич',),
 ('Петрищев Тимофей Максимович',),
 ('Петрова Дарья Сергеевна',),
 ('Петрунин Максим Петрович',),
 ('Погодов Адам Нифонтович',),
 ('Подчасов Максим Никанорович',),
 ('Покалюк Лаврентий Степанович',),
 ('Полкова Юлиана Всеволодовна',),
 ('Полторак Севастьян Кириллович',),
 ('Попов Лев Венедиктович',),
 ('Пузанова Любовь Никитьевна',),
 ('Пушкина Александра Кирилловна',),
 ('Пшеничников Афанасий Васильевич',),
 ('Рабиновича Ирина Ивановна',),
 ('Райт Марианна Трофимовна',),
 ('Редругина Вера Николаевна',),
 ('Романенко Валентина Никифоровна',),
 ('Ростовцев Егор Елизарович',),
 ('Рошета Виктория Ивановна',),
 ('Рудина Алла Юрьевна',),
 ('Русакова Валентина Климентьевна',),
 ('Русакова Марина Петровна',),
 ('Садков Роман Степанович',),
 ('Сальков Макар Аркадинович',),
 ('Саянкин Кирилл Леонидович',),
 ('Седов Игнат Николаевич',),
 ('Сенькина Надежда Федотовна',),
 ('Серёгина Арина Макаровна',),
 ('Сидорова Наталья Васильевна',),
 ('Силаева Светлана Ираклиевна',),
 ('Сиясинов Кирилл Леонтьевич',),
 ('Славакова Анжела Никитьевна',),
 ('Слукина Серафима Максимовна',),
 ('Сонин Савва Геннадьевич',),
 ('Сочинская Валентина Якововна',),
 ('Сухих Людмила Никифоровна',),
 ('Сухиха Юлиана Романовна',),
 ('Сучкова Серафима Ростиславовна',),
 ('Сычёва Лариса Ростиславовна',),
 ('Тарасова Василиса Павловна',),
 ('Травкина Сюзанна Петровна',),
 ('Троицкий Тимофей Юлианович',),
 ('Уицкая Сюзанна Ростиславовна',),
 ('Хабаров Макар Витальевич',),
 ('Халипов Максим Петрович',),
 ('Ховрунов Артем Филиппович',),
 ('Хохлова Мила Себастьяновна',),
 ('Хренова Нина Константиновна',),
 ('Чегодаев Егор Савванович',),
 ('Черкашина Сюзанна Прохор',),
 ('Чиркова Марьяна Ираклиевна',),
 ('Чуличкова Валерия Феоктистовна',),
 ('Швечикова Светлана Петровна',),
 ('Шелепина Василиса Ростиславовна',),
 ('Шерстов Валерий Макарович',),
 ('Шумова Алла Павловна',),
 ('Щенин Яков Филиппович',),
 ('Щередина Анна Константиновна',),
 ('Эпингера Рада Иннокентьевна',),
 ('Ягодин Роман Даниилович',),
 ('Якобсона Раиса Макаровна',),
 ('Яковиченко Пелагея Никитьевна',),
 ('Яковцов Лаврентий Петрович',),
 ('Яковцова Елизавета Трофимовна',),
 ('Якубовский Роман Петрович',),
 ('Якшина Виктория Юрьевна',),
 ('Ямсков Гавриил Максимович',),
 ('Ямщикова Ксения Николаевна',),
 ('Ярочкин Антон Ефимович',),
 ('Ярочкин Юрин Давидович',),
 ('Ярощук Афанасий Михаилович',),
 ('Ясавеева Александра Ефимовна',),
 ('Яхонтов Федор Игнатьевич',),
 ('Яцунова Галина Якововна',)]

Получить из таблицы студентов их ФИО и количество предметов

In [224]:
sqlQuery = """
  SELECT students.surname|| ' ' || students.name as ФИО, faculty.quantity_group as 'Количество предметов'   FROM students
  JOIN groups ON students.group_id = groups.id
  JOIN faculty ON groups.faculty_id = faculty.id
"""
df = pd.read_sql(sqlQuery, con)
df

                                 ФИО  Количество предметов
0          Авдиенко Павел Савванович                     6
1              Агеева Арина Ивановна                     6
2           Алешина Лидия Васильевна                     4
3              Анников Тимофей Ильич                     4
4    Артамонов Константин Елизарович                     6
..                               ...                   ...
154           Ярочкин Юрин Давидович                     6
155       Ярощук Афанасий Михаилович                     6
156     Ясавеева Александра Ефимовна                     3
157         Яхонтов Федор Игнатьевич                     3
158          Яцунова Галина Якововна                     6

[159 rows x 2 columns]

Получить количество студентов каждого факультета

In [232]:
sqlQuery = """
  SELECT  faculty.name as 'Наименование факультета', count(students.id) as 'Количество студентов'  FROM students
  JOIN groups ON students.group_id = groups.id
  JOIN faculty ON groups.faculty_id = faculty.id
  GROUP BY faculty.id
"""
df = pd.read_sql(sqlQuery, con)
df

                             Наименование факультета  Количество студентов
0              Факультет автоматической электросвязи                    40
1     Факультет информатики и вычислительной техники                    29
2       Факультет мобильной радиосвязи и мультимедиа                    60
3  Факультет мультисервисных телекоммуникационных...                    30