In [28]:
import pandas as pd
from datetime import timedelta, datetime

In [29]:
df=pd.read_csv("/content/drive/MyDrive/data/Uber.csv")
df

,Date,Time,State,PuFrom,Address,Street
0,2014.07.06,14:30,NY ...,MANHATTAN,50,MURRAY ST
1,2014.07.04,7:15,NY ...,MANHATTAN,143,AVENUE B
2,2014.07.05,5:45,NY ...,MANHATTAN,125,CHRISTOPHER ST
3,2014.07.06,4:30,NY ...,MANHATTAN,217,E 7 ST
4,2014.07.05,7:45,NY ...,MANHATTAN,521,W 26 ST
...,...,...,...,...,...,...
194987,2014.09.28,21:50,JFK DELTA TERM 4 P/U AREA C ...,Jfk,,
194988,2014.09.28,7:00,NY ...,MANHATTAN,112,W 78 ST
194989,2014.09.28,15:30,NY ...,MANHATTAN,601,W 57 ST
194990,2014.09.28,19:55,JFK DELTA TERM 2 CURBSIDE ...,NaN,,
194991,2014.09.08,9:45,NY ...,MANHATTAN,415,W 24 ST

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194992 entries, 0 to 194991
Data columns (total 6 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Date     194992 non-null  object
 1   Time     194992 non-null  object
 2   State    194992 non-null  object
 3   PuFrom   157962 non-null  object
 4   Address  194992 non-null  object
 5   Street   194992 non-null  object
dtypes: object(6)
memory usage: 8.9+ MB

Удалить строчки с пустыми значениями

In [31]:
df = df.dropna()
df

,Date,Time,State,PuFrom,Address,Street
0,2014.07.06,14:30,NY ...,MANHATTAN,50,MURRAY ST
1,2014.07.04,7:15,NY ...,MANHATTAN,143,AVENUE B
2,2014.07.05,5:45,NY ...,MANHATTAN,125,CHRISTOPHER ST
3,2014.07.06,4:30,NY ...,MANHATTAN,217,E 7 ST
4,2014.07.05,7:45,NY ...,MANHATTAN,521,W 26 ST
...,...,...,...,...,...,...
194986,2014.09.29,6:00,NJ ...,RIDGEWOOD,756,BELMONT RD
194987,2014.09.28,21:50,JFK DELTA TERM 4 P/U AREA C ...,Jfk,,
194988,2014.09.28,7:00,NY ...,MANHATTAN,112,W 78 ST
194989,2014.09.28,15:30,NY ...,MANHATTAN,601,W 57 ST
194991,2014.09.08,9:45,NY ...,MANHATTAN,415,W 24 ST

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 157962 entries, 0 to 194991
Data columns (total 6 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Date     157962 non-null  object
 1   Time     157962 non-null  object
 2   State    157962 non-null  object
 3   PuFrom   157962 non-null  object
 4   Address  157962 non-null  object
 5   Street   157962 non-null  object
dtypes: object(6)
memory usage: 8.4+ MB

Дублирующиеся строки

In [33]:
df.duplicated().describe() # посмотрим есть ли дубликаты

count     157962
unique         2
top        False
freq      156311
dtype: object

In [34]:
df[df.duplicated()] # посмотрим дубликаты

,Date,Time,State,PuFrom,Address,Street
1066,2014.08.18,11:57,NY ...,MANHATTAN,1166,6 AVE
7740,2014.09.01,4:45,NY ...,MANHATTAN,440,E 88 ST
7840,2014.09.18,4:00,NY ...,MANHATTAN,333,E 83 ST
11582,2014.07.15,22:15,NY ...,BRONX,3151,E TREMONT AVE
11795,2014.08.16,17:04,NY ...,MANHATTAN,1166,6 AVE
...,...,...,...,...,...,...
194407,2014.07.24,12:45,NY ...,MANHATTAN,2178,BROADWAY
194585,2014.09.11,14:45,NY ...,MANHATTAN,205,W 39 ST
194647,2014.09.15,13:00,NY ...,MANHATTAN,1535,BROADWAY
194972,2014.08.30,17:15,NY ...,MANHATTAN,102,NORTH END AVE
194983,2014.09.27,18:00,NY ...,BROOKLYN,333,ADAMS ST

In [35]:
df=df.drop(df[df.duplicated()].index, axis=0)# удаление дубликатов

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 156311 entries, 0 to 194991
Data columns (total 6 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Date     156311 non-null  object
 1   Time     156311 non-null  object
 2   State    156311 non-null  object
 3   PuFrom   156311 non-null  object
 4   Address  156311 non-null  object
 5   Street   156311 non-null  object
dtypes: object(6)
memory usage: 8.3+ MB

Переведем данные столбца PuFrom к одному виду

In [37]:
df["PuFrom"]=df["PuFrom"].str.upper()
df["PuFrom"]

0         MANHATTAN
1         MANHATTAN
2         MANHATTAN
3         MANHATTAN
4         MANHATTAN
            ...
194986    RIDGEWOOD
194987          JFK
194988    MANHATTAN
194989    MANHATTAN
194991    MANHATTAN
Name: PuFrom, Length: 156311, dtype: object

Разделим время поездки на два столбца минуты и секунды

In [39]:
df['Time'] = pd.to_datetime(df.Time) # переведем столбей Time в тип datetime
df['hour'] = df['Time'].dt.hour
df['minute'] = df['Time'].dt.minute
df

,Date,Time,State,PuFrom,Address,Street,hour,minute
0,2014.07.06,2023-10-23 14:30:00,NY ...,MANHATTAN,50,MURRAY ST,14,30
1,2014.07.04,2023-10-23 07:15:00,NY ...,MANHATTAN,143,AVENUE B,7,15
2,2014.07.05,2023-10-23 05:45:00,NY ...,MANHATTAN,125,CHRISTOPHER ST,5,45
3,2014.07.06,2023-10-23 04:30:00,NY ...,MANHATTAN,217,E 7 ST,4,30
4,2014.07.05,2023-10-23 07:45:00,NY ...,MANHATTAN,521,W 26 ST,7,45
...,...,...,...,...,...,...,...,...
194986,2014.09.29,2023-10-23 06:00:00,NJ ...,RIDGEWOOD,756,BELMONT RD,6,0
194987,2014.09.28,2023-10-23 21:50:00,JFK DELTA TERM 4 P/U AREA C ...,JFK,,,21,50
194988,2014.09.28,2023-10-23 07:00:00,NY ...,MANHATTAN,112,W 78 ST,7,0
194989,2014.09.28,2023-10-23 15:30:00,NY ...,MANHATTAN,601,W 57 ST,15,30
194991,2014.09.08,2023-10-23 09:45:00,NY ...,MANHATTAN,415,W 24 ST,9,45

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 156311 entries, 0 to 194991
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Date     156311 non-null  object
 1   Time     156311 non-null  datetime64[ns]
 2   State    156311 non-null  object
 3   PuFrom   156311 non-null  object
 4   Address  156311 non-null  object
 5   Street   156311 non-null  object
 6   hour     156311 non-null  int64
 7   minute   156311 non-null  int64
dtypes: datetime64[ns](1), int64(2), object(5)
memory usage: 10.7+ MB

In [55]:
df["Time, min"]= round((df["hour"] + (df["minute"]/60)), 2)
df

,Date,Time,State,PuFrom,Address,Street,hour,minute,"Time, min"
0,2014.07.06,2023-10-23 14:30:00,NY ...,MANHATTAN,50,MURRAY ST,14,30,14.50
1,2014.07.04,2023-10-23 07:15:00,NY ...,MANHATTAN,143,AVENUE B,7,15,7.25
2,2014.07.05,2023-10-23 05:45:00,NY ...,MANHATTAN,125,CHRISTOPHER ST,5,45,5.75
3,2014.07.06,2023-10-23 04:30:00,NY ...,MANHATTAN,217,E 7 ST,4,30,4.50
4,2014.07.05,2023-10-23 07:45:00,NY ...,MANHATTAN,521,W 26 ST,7,45,7.75
...,...,...,...,...,...,...,...,...,...
194986,2014.09.29,2023-10-23 06:00:00,NJ ...,RIDGEWOOD,756,BELMONT RD,6,0,6.00
194987,2014.09.28,2023-10-23 21:50:00,JFK DELTA TERM 4 P/U AREA C ...,JFK,,,21,50,21.83
194988,2014.09.28,2023-10-23 07:00:00,NY ...,MANHATTAN,112,W 78 ST,7,0,7.00
194989,2014.09.28,2023-10-23 15:30:00,NY ...,MANHATTAN,601,W 57 ST,15,30,15.50
194991,2014.09.08,2023-10-23 09:45:00,NY ...,MANHATTAN,415,W 24 ST,9,45,9.75

Удалим ненужные столбцы

In [56]:
df= df.drop(['Time', 'hour', 'minute'], axis=1)
df

,Date,State,PuFrom,Address,Street,"Time, min"
0,2014.07.06,NY ...,MANHATTAN,50,MURRAY ST,14.50
1,2014.07.04,NY ...,MANHATTAN,143,AVENUE B,7.25
2,2014.07.05,NY ...,MANHATTAN,125,CHRISTOPHER ST,5.75
3,2014.07.06,NY ...,MANHATTAN,217,E 7 ST,4.50
4,2014.07.05,NY ...,MANHATTAN,521,W 26 ST,7.75
...,...,...,...,...,...,...
194986,2014.09.29,NJ ...,RIDGEWOOD,756,BELMONT RD,6.00
194987,2014.09.28,JFK DELTA TERM 4 P/U AREA C ...,JFK,,,21.83
194988,2014.09.28,NY ...,MANHATTAN,112,W 78 ST,7.00
194989,2014.09.28,NY ...,MANHATTAN,601,W 57 ST,15.50
194991,2014.09.08,NY ...,MANHATTAN,415,W 24 ST,9.75